tkhwang/readable

.prettierrc

💄 (common): Setup prettier rule

---

apps/client/webpack.config.js
workspace.json

- custom webpack 설정을 위한 `webpack.config.js` 파일 추가 후 `workspace.json` 파일에 적용

🔧 (client): Setup a custom webpack

---

apps/server/src/app.module.ts
apps/server/src/graphql-types.gql
apps/server/src/users/entities/user.entity.ts
apps/server/tsconfig.json

* User module 이제 시작
* 기본 authentication 준비 예정.

♻️  (server): Setup User module

---

apps/client/postcss.config.js
apps/client/src/app/app.tsx
apps/client/src/styles.css
apps/client/tailwind.config.js
apps/client/webpack.config.js
package.json
workspace.json
yarn.lock

- tailwind 설치 후 webpack 설정
- tailwind 동작 확인

➕(client): Setup tailwind

---

apps/client-next/codegen.yml
apps/client-next/components/GetUsersViewController.tsx
apps/client-next/components/useGetUsersViewModel.query.generated.tsx
apps/client-next/components/useGetUsersViewModel.query.ts
apps/client-next/core/ViewController.ts
apps/client-next/core/ViewModel.ts
apps/client-next/lib/withApollo.tsx
apps/client-next/pages/_app.tsx
apps/client-next/pages/index.tsx
apps/client-next/src/graphql-types.ts
apps/client-next/src/link.ts
apps/client-next/tsconfig.json
package.json
yarn.lock

* Ref: https://www.youtube.com/watch?v=4yDrtFUbUzo&t=541s

🌱 (client-next): Setup apollo client and codegen in nx next.js app

---

apps/server/src/app.module.ts
apps/server/src/auth/auth.controller.ts
apps/server/src/auth/auth.service.ts
apps/server/src/auth/facebook.strategy.ts
package.json
yarn.lock

🛂 (server): Add facebook social login

---

.github/PULL_REQUEST_TEMPLATE.md

Add PR template
**Test Configuration**:
- Client:
- Server:

👷 (common): Add PR template

---

apps/server/src/app.module.ts
apps/server/src/common/entities/core.entity.ts
apps/server/src/common/repositories/index.ts
apps/server/src/graphql-types.gql
apps/server/src/jwt/jwt.constants.ts
apps/server/src/jwt/jwt.interface.ts
apps/server/src/jwt/jwt.middleware.ts
apps/server/src/jwt/jwt.module.ts
apps/server/src/jwt/jwt.service.spec.ts
apps/server/src/jwt/jwt.service.ts
apps/server/src/users/entities/user.entity.ts
apps/server/src/users/users.module.ts
apps/server/src/users/users.repository.ts
apps/server/src/users/users.resolver.ts
apps/server/src/users/users.service.ts

🛂  (server): Add JwtModule

---

apps/server/src/auth/auth.controller.ts
apps/server/src/auth/auth.service.ts
apps/server/src/auth/strategies/facebook.strategy.ts
apps/server/src/auth/strategies/github.strategy.ts
apps/server/src/auth/strategies/google.strategy.ts
apps/server/src/common/repositories/index.ts
apps/server/src/graphql-types.gql
apps/server/src/users/dto/create-user.input.ts
apps/server/src/users/dto/update-user.input.ts
apps/server/src/users/entities/user.entity.ts
apps/server/src/users/users.error.ts
apps/server/src/users/users.repository.ts
apps/server/src/users/users.resolver.ts
apps/server/src/users/users.service.ts

Issue jwt token for social signin.

🛂 (server): Issue jwt token

---

.github/PULL_REQUEST_TEMPLATE.md
apps/client/components/SocialLoginButton/index.tsx
apps/client/lib/withApollo.tsx
apps/client/src/link.ts

🔧 (client): Use SERVER_HOST environment variable

---

apps/client/common/constants.ts
apps/client/common/link.ts
apps/client/components/modules/Header.js
apps/client/lib/withApollo.tsx
apps/client/pages/_app.tsx
apps/client/pages/auth.tsx
apps/client/pages/index.tsx
apps/client/pages/logout.tsx

* client JWT, auth and login handling
* Apollo reactive variable 사용에 대해서는 향후 좀더 논의 예정. 우선 사용법 공유를 위하여 반영함.

🛂 (client): Auth/login handling

---

apps/client/common/auth.ts
apps/client/errors/auth.ts
apps/client/pages/_app.tsx
apps/client/pages/auth.tsx
apps/client/pages/logout.tsx

* auth, localStorage handling codes are extracted into function.

♻️ (client): Refactor client auth code

---

apps/server/src/auth/auth.controller.ts
apps/server/src/auth/auth.service.ts
apps/server/src/auth/auth.type.ts
apps/server/src/common/repositories/index.ts
apps/server/tsconfig.app.json
apps/server/tsconfig.json
tsconfig.base.json

* Not using strict mode yet. 
* First fix server type error before enabling strict mode

🏷️ (server): Fix type error

---

apps/server/src/auth/auth.service.ts
apps/server/src/auth/auth.type.ts
apps/server/src/bookmarks/bookmarks.module.ts
apps/server/src/bookmarks/bookmarks.repository.ts
apps/server/src/bookmarks/bookmarks.resolver.ts
apps/server/src/bookmarks/infrastructures/mongo/bookmark.entity.ts
apps/server/src/bookmarks/models/bookmark.entity.builder.ts
apps/server/src/bookmarks/models/bookmark.model.ts
apps/server/src/bookmarks/usecases/get-url-info/get-url-info.usecase.ts
apps/server/src/common/infrastructures/mongo/entities/index.ts
apps/server/src/common/infrastructures/mongo/repositories/index.ts
apps/server/src/common/models/core.model.ts
apps/server/src/common/usecase/index.ts
apps/server/src/users/dto/create-user.input.ts
apps/server/src/users/infrastructures/mongo/user.entity.ts
apps/server/src/users/models/user.model.ts
apps/server/src/users/users.module.ts
apps/server/src/users/users.repository.ts
apps/server/src/users/users.resolver.ts
apps/server/src/users/users.service.ts

* MongoDB/Mongoose 가 계속 문제가 되서 typeorm 으로 이전해야할 듯.
* 그 전에 `infrastructure` layer 로 분리하여 DB 도 쉽게 바꿀 수 있는 구조 구축.
* Disable mongodb.
* Enable typeorm.
* 🙏

🏗️ (server): Use infrastructure layer

---

apps/server/src/app.module.ts
apps/server/src/common/infrastructures/typeorm/entities/index.ts
apps/server/src/common/models/core.model.ts
apps/server/src/graphql-types.gql
apps/server/src/users/infrastructures/mongo/user.entity.ts
apps/server/src/users/infrastructures/typeorm/user.entity.ts
apps/server/src/users/models/user.model.ts

🗃 (server): Basic preparation for typeorm usage

---

apps/client/components/layout.tsx
apps/client/components/modules/Bookmarks/Bookmarks.tsx
apps/client/components/modules/Bookmarks/BookmarksViewController.tsx
apps/client/components/modules/Bookmarks/useBookmarks.query.generated.tsx
apps/client/components/modules/Bookmarks/useBookmarks.query.tsx
apps/client/components/modules/Home/index.tsx
apps/client/components/modules/HomeComp/HomeComp.tsx
apps/client/components/modules/HomeComp/index.ts
apps/client/components/modules/Me/MeViewController.tsx
apps/client/components/modules/Me/index.tsx
apps/client/pages/index.tsx
apps/client/types/graphql-types.ts
apps/server/src/app.module.ts
apps/server/src/bookmarks/bookmarks.controller.spec.ts
apps/server/src/bookmarks/bookmarks.controller.ts
apps/server/src/bookmarks/bookmarks.module.ts
apps/server/src/bookmarks/bookmarks.resolver.spec.ts
apps/server/src/bookmarks/bookmarks.resolver.ts
apps/server/src/bookmarks/infrastructures/typeorm/bookmark.entity.builder.ts
apps/server/src/bookmarks/infrastructures/typeorm/bookmark.entity.ts
apps/server/src/bookmarks/models/bookmark.model.ts
apps/server/src/bookmarks/usecases/add-bookmark/add-bookmark.input.ts
apps/server/src/bookmarks/usecases/add-bookmark/add-bookmark.usecase.ts
apps/server/src/bookmarks/usecases/get-bookmarks/get-bookmarks.usecase.ts
apps/server/src/graphql-types.gql
apps/server/src/users/infrastructures/typeorm/user.entity.ts
apps/server/src/users/users.module.ts
apps/server/src/users/users.resolver.ts
apps/server/src/users/users.service.ts

✨  (server,client): bookmark PoC

---

apps/client/components/modules/Bookmarks/BookmarkCard.tsx
apps/client/components/modules/Bookmarks/BookmarksViewController.tsx
apps/client/components/modules/Bookmarks/useBookmarks.query.generated.tsx
apps/client/components/modules/Bookmarks/useBookmarks.query.tsx
apps/client/types/graphql-types.ts
apps/server/src/app.module.ts
apps/server/src/bookmarks/bookmarks.controller.ts
apps/server/src/bookmarks/bookmarks.module.ts
apps/server/src/bookmarks/bookmarks.resolver.ts
apps/server/src/bookmarks/infrastructures/typeorm/bookmark.entity.builder.ts
apps/server/src/bookmarks/infrastructures/typeorm/bookmark.entity.ts
apps/server/src/bookmarks/usecases/add-bookmark-with-auth/add-bookmark-with-auth.input.ts
apps/server/src/bookmarks/usecases/add-bookmark-with-auth/add-bookmark-with-auth.usecase.ts
apps/server/src/bookmarks/usecases/add-bookmark/add-bookmark.usecase.ts
apps/server/src/bookmarks/usecases/get-anonymous-bookmarks/get-anonymous-bookmarks.usecase.ts
apps/server/src/bookmarks/usecases/get-bookmarks/get-bookmarks.usecase.ts
apps/server/src/bookmarks/usecases/get-my-bookmarks/get-my-bookmarks.usecase.ts
apps/server/src/bookmarks/usecases/get-urlinfo/get-urlinfo.input.ts
apps/server/src/bookmarks/usecases/get-urlinfo/get-urlinfo.usecase.ts
apps/server/src/graphql-types.gql
apps/server/src/users/infrastructures/typeorm/user.entity.ts
apps/server/src/users/users.module.ts
apps/server/src/users/users.service.ts

✨  (server,client): Add bookmark related usecases (myBookmarks, anonymousBookmarks, ...)

---

apps/server/src/bookmarks/usecases/get-urlinfo/get-urlinfo.usecase.ts

* URL 정보 확인 시 기존 DB 정보 있는 경우에는 저장된 내용을 Return 하도록 함.

✨ (server): Check URL duplication

---

apps/server/src/graphql-types.gql
apps/server/src/users/application/usecases/signin/signin.usecase.ts
apps/server/src/users/domain/oauthUser.model.ts
apps/server/src/users/domain/user.model.ts
apps/server/src/users/infrastructures/typeorm/entities/oauthUser.entity.ts
apps/server/src/users/infrastructures/typeorm/entities/user.entity.ts

♻️  (server): Refactor user domain (oauthUser/user)

---

apps/client/components/modules/Bookmarks/BookmarksViewController.tsx
apps/client/components/modules/Bookmarks/useBookmarks.query.generated.tsx
apps/client/components/modules/Bookmarks/useBookmarks.query.tsx
apps/client/types/graphql-types.ts
apps/server/src/bookmarks/applications/usecases/delete-bookmark-with-auth/delete-bookmark-with-auth.usecase.ts

* Add `deleteBookmarkWithAuth` usecase

✨ (server): Add deleteBookmark usecase 

---

libs/home/feature-home/src/lib/home/home.tsx

* 현재 auth expired 된 경우에 login 할 수 있는 방법이 없음.
* unauthorized 인 경우에 /login page 로 이동시키기

🛂 (client): When unthorized, move to login page

---

apps/client/pages/_document.tsx
apps/client/tsconfig.json
apps/server/tsconfig.json
libs/shared/util-auth/src/lib/auth.ts
tsconfig.base.json

* Enable missing typescript `strict` mode.

💥 (common):  Apply typescript strict mode

---

apps/client/codegen.yml
apps/client/types/graphql-types.ts
libs/bookmark/data-access-bookmark/src/lib/useBookmarks.query.generated.tsx
libs/shared/data-access-auth/src/lib/useAuth.query.generated.tsx
libs/shared/data-access-me/src/lib/useMeViewModel.query.generated.tsx

* 새로운 NX 환경에서 codegen 동작하도록 수정하기

🔧 (client): Fix codegen problem

---

apps/server/src/bookmarks/domain/models/bookmark.model.ts
apps/server/src/bookmarks/infrastructures/typeorm/entities/bookmark.entity.ts
apps/server/src/graphql-types.gql
libs/collection/data-access-bookmark/src/lib/useBookmarks.query.generated.tsx
libs/collection/data-access-bookmark/src/lib/useBookmarks.query.tsx
libs/collection/feature-bookmark/src/lib/BookmarksViewController.tsx
libs/shared/data-access-user/src/types/graphql-types.ts
libs/shared/types/src/lib/graphql-types.ts

🔥 (server,client): Remove unused code

---

.eslintrc.json
.vscode/settings.json

- React Hooks, dependencies 관련 rule 추가
- nrwl lint 에러 해결

🔧 (client): React 관련 lint 설정 추가 및 기타 lint 에러 해결

---

apps/server/src/graphql-types.gql
apps/server/src/interests/applications/usecases/get-my-interests-with-auth/get-my-interests-with-auth.usecase.ts
apps/server/src/interests/interests.controller.ts
apps/server/src/interests/interests.module.ts
apps/server/src/interests/interests.resolver.ts

✨  (server): Add myInterests GraphQL/REST router

---

apps/server/src/bookmarks/bookmarks.controller.ts
apps/server/src/bookmarks/bookmarks.module.ts
apps/server/src/bookmarks/bookmarks.service.ts

* 기존 `/urlInfo` 에 다른 정보를 한 꺼번에 전송하기
*  `tags`
*  `summary`
```
POST /urlInfo
{
"url": "https://javascript.plainenglish.io/45-best-app-ideas-for-startups-bonus-ideas-to-make-money-in-2021-5d200a59a6d0"
}
{
"urlInfo": {
"url": "https://javascript.plainenglish.io/45-best-app-ideas-for-startups-bonus-ideas-to-make-money-in-2021-5d200a59a6d0",
"siteName": "Medium",
"title": "45+ Best App Ideas for Startups + Bonus Ideas to Make Money in 2021",
"type": "article",
"imageUrl": "https://miro.medium.com/max/900/1*MFZkhIO31lWfy7237_YBXg.jpeg",
"description": "With the increasing usage of the internet, undoubtedly mobile usage has also increased by tenfold and people have started spending 3 hours…",
"urlHash": "0f711f29fd0f9054aa33ae8031b2ba39ffbf38d9c8001470d6621276be458fd4",
"howMany": 0
}, …
```

♻️ (server): Use integrated getUrlInfo call for extensions

---

apps/server/src/bookmarks/applications/usecases/add-bookmark-with-auth/add-bookmark-with-auth.usecase.ts
apps/server/src/bookmarks/applications/usecases/get-urlinfo/get-urlinfo.usecase.ts
apps/server/src/bookmarks/bookmarks.service.ts

* Extract basic information when ogTag is not available : `url`, `siteName`
Extension 에서 URL 등록 시
등록 시 bookmark 정보

♻️ (server): Extract basic information when ogTag is not available

---

apps/server/src/bookmarks/applications/usecases/add-bookmark-with-auth/add-bookmark-with-auth.input.ts
apps/server/src/bookmarks/applications/usecases/add-bookmark-with-auth/add-bookmark-with-auth.usecase.ts
apps/server/src/bookmarks/bookmarks.controller.ts
apps/server/src/bookmarks/bookmarks.module.ts
apps/server/src/graphql-types.gql
apps/server/src/interests/applications/usecases/find-or-add-interest/find-or-add-interest-with-auth.input.ts
apps/server/src/interests/interests.module.ts
libs/shared/types/src/lib/graphql-types.ts

* Bookmark 등록 시 input paramter type 변경
- `interest: string` 
- `tags?: string[]`
```
{
"url": "https://dev.to/zernonia/supabase-storage-cdn-and-transformation-with-serverless-function-unofficial-go",
"interest": "MicroServices",
"tags": ["first", "second" ]
}
{
"id": "eaaa8721-b1ee-4151-b235-928598e4e680",
"createdAt": "2021-09-10T22:12:12.713Z",
"updatedAt": "2021-09-10T22:12:12.713Z",
"deletedAt": null,
"url": "https://dev.to/zernonia/supabase-storage-cdn-and-transformation-with-serverless-function-unofficial-go",
"siteName": "DEV Community",
"title": "Supabase Storage CDN and Transformation with Serverless function (Unofficial)",
"type": "article",
"urlHash": "735f62eca0688337578826318270c0bdf3d7330ad31820ba27711515def5a351",
"description": "This tutorial is just a temporary …
```

♻️ (server): Change to take interest as string type for registering bookmark

---

apps/server/src/graphql-types.gql
apps/server/src/users/applications/usecases/follow-user-with-auth/follow-user-with-auth.output.ts
apps/server/src/users/applications/usecases/follow-user-with-auth/follow-user-with-auth.usecase.ts
apps/server/src/users/applications/usecases/unfollow-user-with-auth/unfollow-user-with-auth.output.ts
apps/server/src/users/applications/usecases/unfollow-user-with-auth/unfollow-user-with-auth.usecase.ts
apps/server/src/users/domain/models/user.model.ts
apps/server/src/users/users.resolver.ts

* Refactor follow/unfollow usecase.
* Use only followersCount and followingsCount instead of its lists.

♻️ (server): Refactor User model field resolver

---

libs/feed/data-access-pagination-bookmarks/src/lib/usePaginationUserBookmarks.query.generated.tsx
libs/feed/data-access-pagination-bookmarks/src/lib/usePaginationUserBookmarks.query.tsx
libs/home/data-access-home/src/lib/data-access-feed.query.generated.tsx
libs/home/data-access-home/src/lib/data-access-feed.query.tsx
libs/shared/types/src/lib/graphql-types.ts

♻️ (libs): Codegen updated

---

apps/server/src/graphql-types.gql
apps/server/src/pagination/paginationUserBookmarks/applications/usecases/get-pagination-user-bookmarks/get-pagination-user-bookmarks.input.ts
apps/server/src/pagination/paginationUserBookmarks/applications/usecases/get-pagination-user-bookmarks/get-pagination-user-bookmarks.usecase.ts
apps/server/src/pagination/paginationUserBookmarks/domain/models/paginationUserBookmarks.filter.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts
libs/shared/types/src/lib/graphql-types.ts

* Add user `interest` filter  in `paginationUserBookmarks`

✨ (server,libs): Add user interest filter in pagination query

---

apps/server/src/graphql-types.gql
apps/server/src/user-bookmark/applications/usecases/delete-user-bookmark-with-auth/delete-user-bookmark-with-auth.input.ts
apps/server/src/user-bookmark/applications/usecases/delete-user-bookmark-with-auth/delete-user-bookmark-with-auth.usecase.ts
apps/server/src/user-bookmark/applications/usecases/get-my-user-bookmarks-with-auth/get-my-user-bookmarks-with-auth.usecase.ts
apps/server/src/user-bookmark/domain/errors/user-bookmark.error.ts
apps/server/src/user-bookmark/user-bookmark.module.ts
apps/server/src/user-bookmark/user-bookmark.resolver.ts
libs/collection/data-access-bookmark/src/lib/useUserBookmarks.query.generated.tsx
libs/collection/data-access-bookmark/src/lib/useUserBookmarks.query.tsx
libs/collection/feature-bookmark/src/lib/BookmarksViewController.tsx
libs/shared/types/src/lib/graphql-types.ts

* Add `deleteUserBookmark` usecase

✨ (server,libs): Add delete userBookmark usecase

---

apps/server/src/graphql-types.gql
apps/server/src/pagination/paginationUserBookmarks/domain/models/paginationUserBookmarks.model.ts
apps/server/src/user-bookmark/domain/model/user-bookmark.model.ts
apps/server/src/user-bookmark/infrastructures/typeorm/entities/user-bookmark.entity.ts
apps/server/src/user-bookmark/user-bookmark.resolver.ts
apps/server/src/user-bookmark/user-bookmark.service.ts
libs/collection/data-access-bookmark/src/lib/useUserBookmarks.query.generated.tsx
libs/collection/data-access-bookmark/src/lib/useUserBookmarks.query.tsx
libs/feed/data-access-pagination-bookmarks/src/lib/usePaginationUserBookmarks.query.generated.tsx
libs/feed/data-access-pagination-bookmarks/src/lib/usePaginationUserBookmarks.query.tsx
libs/feed/feature-bookmark/src/lib/BookmarksViewController.tsx
libs/shared/types/src/lib/graphql-types.ts

✨  (server): Add bookmarkers and readers in userBookmark field resolver

---

apps/server/src/graphql-types.gql
apps/server/src/pagination/pagination.module.ts
apps/server/src/pagination/paginationUserBookmarks/applications/usecases/get-pagination-user-bookmarks/get-pagination-user-bookmarks.usecase.ts
apps/server/src/pagination/paginationUserBookmarks/domain/models/paginationUserBookmarks.filter.ts
apps/server/src/tags/domain/erros/tag.error.ts
apps/server/src/tags/domain/models/tag.model.ts
apps/server/src/tags/infrastructures/typeorm/entities/tags.entity.ts
apps/server/src/tags/tags.service.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts
apps/server/src/user-bookmark/user-bookmark.service.ts
package.json
yarn.lock

- lowercase
- `.js` 에서 `.js` 삭제하여 `react.js` , `React.js`, `react` 가 모두 내부적으로는 `react` tag 사용하도록 함.
`tag` 호환성을 높이기 위하여 `normalizedTag` 로 preprocessing 처리하여 이용하도록 함.

✨ (server): Use normalizedTag in Tag domain

---

libs/home/feature-home/src/lib/feature-home.tsx
libs/home/feature-home/src/lib/home-header.tsx
libs/ui/src/lib/logo/logo.tsx
libs/ui/src/lib/shadow-card/shadow-card.tsx

- shadow-card Next.js 이미지 컴포넌트 적용

💄 (client): home page에 반응형 layout 적용

---

libs/home/feature-home/src/lib/home-feed.tsx
libs/ui/src/lib/shadow-card/shadow-card.tsx

- 알록달록...tag마다? 고유 컬러가 정해지기 전까지 index를 기준으로한 랜덤 컬러 적용!

💄 (client): home page feed card 임시 랜덤 컬러 적용

---

libs/home/feature-home/src/lib/feature-home.tsx
libs/home/feature-home/src/lib/home-header.tsx
libs/ui/src/lib/shadow-card/shadow-card.tsx

- 네비게이션, 검색 접근성 향상을 위한 header fixed 처리!
- feed card 가독성을 위해 break-word 처리!

♿️ (client): home page header fixed 처리

---

libs/home/feature-home/src/lib/feature-home.tsx
libs/ui/src/lib/shadow-card/shadow-card.tsx

- home page feed card bg-color 배포 환경에서 적용안되는 문제 해결
- home page feed card 내용, 이미지 비율 변경
- 모바일 사이즈 좌우 padding 변경

🐛 (client): 배포 환경에서 bg-color 적용 안되는 문제 해결

---

apps/client/pages/index.tsx
libs/ui/src/index.ts
libs/ui/src/lib/loading/loading.stories.tsx
libs/ui/src/lib/loading/loading.tsx
tailwind.config.js

- 궁금하면 loading 화면 눈 크게 뜨고 확인 ㅎ.ㅎ

💄 (client): 임시 Loading UI 적용

---

libs/ui/src/lib/shadow-card/shadow-card.tsx

- 프로덕션에서 bg-color 적용안되는 문제 해결 중

🐛 (client): shadow-card class 이름 문자열 연결 제거

---

libs/home/data-access-home/src/lib/data-access-feed.query.tsx
libs/home/feature-home/src/lib/home-feed.tsx
libs/ui/src/lib/shadow-card/shadow-card.tsx

- homepage feed card에 urlInfo title data를 적용하였습니다.

💄 (client): shadow-card(homepage feed card)에 title data 적용

---

apps/server/src/app.module.ts
apps/server/src/pagination/pagination.module.ts
apps/server/src/pagination/pagination.service.spec.ts
apps/server/src/pagination/pagination.service.ts
apps/server/src/pagination/paginationUserBookmarks/applications/usecases/get-pagination-user-bookmarks/get-pagination-user-bookmarks.usecase.ts
apps/server/src/pagination/paginationUserBookmarks/domain/models/paginationUserBookmarks.model.ts
apps/server/src/pagination/paginationUserBookmarks/paginationUserBookmarks.service.ts
apps/server/src/recommend/recommend.module.ts
apps/server/src/recommend/recommend.service.spec.ts
apps/server/src/recommend/recommend.service.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts

* Extract common pagination service for generating various paginations

♻️  (server): Extract pagination service for various paginations

---

apps/server/src/pagination/paginationUserBookmarks/paginationUserBookmarks.service.ts
apps/server/src/recommend/applications/usecases/recommend-user-bookmarks-by-tags/recommend-user-bookmarks-by-tags.input.ts
apps/server/src/recommend/applications/usecases/recommend-user-bookmarks-by-tags/recommend-user-bookmarks-by-tags.output.ts
apps/server/src/recommend/applications/usecases/recommend-user-bookmarks-by-tags/recommend-user-bookmarks-by-tags.usecase.ts
apps/server/src/recommend/recommend.module.ts
apps/server/src/user-bookmark/applications/usecases/add-user-bookmark-with-auth/add-user-bookmark-with-auth.usecase.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts
apps/server/src/user-bookmark/user-bookmark.module.ts
apps/server/src/user-bookmark/user-bookmark.service.ts

* Add recommend module
* Add add-user-bookmarks-by-tags usecase

✨  (server): Add recommend module of add-user-bookmarks-by-tags usecase

---

apps/server/src/tags/applications/usercases/initialize-tags/initialize-tags.usecase.ts
apps/server/src/tags/applications/usercases/map-tags/map-tags.input.ts
apps/server/src/tags/applications/usercases/map-tags/map-tags.usecase.ts
apps/server/src/tags/tags.module.ts
apps/server/src/tags/tags.service.ts
apps/server/src/user-bookmark/applications/usecases/add-user-bookmark-with-auth/add-user-bookmark-with-auth.usecase.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts

♻️  (server): Add createIndexDocument when adding tag

---

apps/server/src/graphql-types.gql
apps/server/src/pagination/tags/applications/usecases/get-pagination-tags/get-pagination-tags.usecase.ts
apps/server/src/pagination/tags/paginationTags.resolver.ts
apps/server/src/tags/domain/models/tag.model.ts
apps/server/src/tags/tags.module.ts
apps/server/src/tags/tags.resolver.spec.ts
apps/server/src/tags/tags.resolver.ts
apps/server/src/tags/tags.service.ts
apps/server/src/users/domain/models/user.model.ts
apps/server/src/users/infrastructures/typeorm/entities/user.entity.ts
libs/mvp-tag/data-access-tag/src/lib/usePaginationTags.query.generated.tsx
libs/mvp-tag/data-access-tag/src/lib/usePaginationTags.query.tsx
libs/mvp-tag/feature-tag/src/lib/TagPage.tsx
libs/shared/types/src/lib/graphql-types.ts

✨  (server,libs): Add tag field resolver - userBookmarksCount, followersCount

---

apps/server/src/pagination/pagination.service.ts

* Pagination offset by one error fix.

🐛 (server): Fix pagination offset error

---

apps/server/src/pagination/pagination.service.ts

🐛 (server): Apply workaround for pagination problem

---

apps/client/pages/mvpSearch.tsx
apps/client/tsconfig.json
jest.config.js
libs/home/feature-home/src/lib/home-sidebar.tsx
libs/mvp-search/data-access-search/.babelrc
libs/mvp-search/data-access-search/.eslintrc.json
libs/mvp-search/data-access-search/README.md
libs/mvp-search/data-access-search/jest.config.js
libs/mvp-search/data-access-search/src/index.ts
libs/mvp-search/data-access-search/src/lib/useSearchTextInALlUrlinfos.query.generated.tsx
libs/mvp-search/data-access-search/src/lib/useSearchTextInALlUrlinfos.query.tsx
libs/mvp-search/data-access-search/tsconfig.json
libs/mvp-search/data-access-search/tsconfig.lib.json
libs/mvp-search/data-access-search/tsconfig.spec.json
libs/mvp-search/feature-search/.babelrc
libs/mvp-search/feature-search/.eslintrc.json
libs/mvp-search/feature-search/README.md
libs/mvp-search/feature-search/jest.config.js
libs/mvp-search/feature-search/src/index.ts
libs/mvp-search/feature-search/src/lib/SearchPage.tsx
libs/mvp-search/feature-search/tsconfig.json
libs/mvp-search/feature-search/tsconfig.lib.json
libs/mvp-search/feature-search/tsconfig.spec.json
nx.json
tsconfig.base.json
workspace.json

* Search 기능 demo 를 위한 Search MVP page 추가하기

✨  (client,libs): Add Search MVP page for demonstrating search feature

---

apps/server/src/graphql-types.gql
apps/server/src/url-info/applications/usecases/extract-url-info/extract-url-info.usecase.ts
apps/server/src/url-info/domain/model/url-info.model.ts
apps/server/src/url-info/infrastructures/typeorm/entities/url-info.entity.builder.ts
apps/server/src/url-info/infrastructures/typeorm/entities/url-info.entity.ts
apps/server/src/user-bookmark/applications/usecases/add-user-bookmark-with-auth/add-user-bookmark-with-auth.usecase.ts
libs/feed/data-access-pagination-bookmarks/src/lib/usePaginationUserBookmarks.query.generated.tsx
libs/feed/data-access-pagination-bookmarks/src/lib/usePaginationUserBookmarks.query.tsx
libs/feed/feature-bookmark/src/lib/BookmarksViewController.tsx
libs/shared/types/src/lib/graphql-types.ts
package.json
yarn.lock

Add favicon extraction when registering urlinfo
- [ㅌ] ✨ New feature (non-breaking change which adds new functionality)

✨  (server): Add favicon extraction when registering urlinfo

---

apps/client/pages/index.tsx
libs/shared/data-access-me/src/lib/useMe.query.tsx

- 페이지 최상단 쿼리는 cache fetchPolicy network-only로 수정
- 나머지 쿼리는 cache fetchPolicy default 값 적용

⚡️ (client): Fix a problem that is captured multiple times in the network for me query

---

apps/server/src/graphql-types.gql
apps/server/src/pagination/pagination.service.ts
apps/server/src/tags/applications/usercases/follow-tag-with-auth/follow-tag-with-auth.input.ts
apps/server/src/tags/applications/usercases/follow-tag-with-auth/follow-tag-with-auth.output.ts
apps/server/src/tags/applications/usercases/follow-tag-with-auth/follow-tag-with-auth.usecase.ts
apps/server/src/tags/domain/erros/tag.error.ts
apps/server/src/tags/domain/models/tag.model.ts
apps/server/src/tags/tags.module.ts
apps/server/src/tags/tags.resolver.ts
apps/server/src/tags/tags.service.ts
apps/server/src/user-bookmark/applications/usecases/sync-google-calendar-with-auth/sync-google-calendar-with-auth.usecase.ts
apps/server/src/user-bookmark/user-bookmark.service.ts
apps/server/src/users/applications/usecases/follow-user-with-auth/follow-user-with-auth.usecase.ts
apps/server/src/users/applications/usecases/unfollow-user-with-auth/unfollow-user-with-auth.usecase.ts
apps/server/src/users/domain/errors/oauthUser.error.ts
apps/server/src/users/domain/errors/users.error.ts
apps/server/src/users/users.resolver.ts
apps/server/src/users/users.service.ts
libs/mvp-tag/data-access-tag/src/index.ts
libs/mvp-tag/data-access-tag/src/lib/useFollowTag.mutation.generated.tsx
libs/mvp-tag/data-access-tag/src/lib/useFollowTag.mutation.tsx
libs/mvp-tag/data-access-tag/src/lib/usePaginationTags.query.generated.tsx
libs/mvp-tag/data-access-tag/src/lib/usePaginationTags.query.tsx
libs/mvp-tag/feature-tag/src/lib/TagPage.tsx
libs/mvp-tag/input-tag/src/lib/mvp-tag-input-tag.tsx
libs/shared/data-access-me/src/lib/useMe.query.generated.tsx
libs/shared/data-access-me/src/lib/useMe.query.tsx
libs/shared/types/src/lib/graphql-types.ts

ure that would cause existing functionality to not work as expected)

✨  (server,client,libs): Add follow tag feature

---

apps/server/src/graphql-types.gql
apps/server/src/pagination/userBookmarks/applications/usecases/get-pagination-user-bookmarks/get-pagination-user-bookmarks.usecase.ts
apps/server/src/tags/domain/models/tag.model.ts
apps/server/src/tags/infrastructures/typeorm/entities/tags.entity.ts
apps/server/src/tags/infrastructures/typeorm/repositories/tags.repository.ts
apps/server/src/user-bookmark/infrastructures/typeorm/entities/user-bookmark.entity.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts

🗃️ (server): Set bi-directional relations between tags and userBookmarks

---

apps/server/src/graphql-types.gql
apps/server/src/tags/applications/usercases/get-popular-tags-with-auth/get-popular-tags-with-auth.input.ts
apps/server/src/tags/applications/usercases/get-popular-tags-with-auth/get-popular-tags-with-auth.usecase.ts
apps/server/src/tags/infrastructures/typeorm/repositories/tags.repository.ts
apps/server/src/tags/tags.module.ts
apps/server/src/tags/tags.resolver.ts

popular tags query 추가하기
* No pagiation.
* `howMany` parameter input 받아서 가장 유명한 `howMany` 개의 popular tag 조회
```
query PpopularTags($getPopularTagsWithAuthInput: GetPopularTagsWithAuthInput!) {
popularTags(getPopularTagsWithAuthInput: $getPopularTagsWithAuthInput) {
id
tag
normalizedTag
imageUrl
followersCount
userBookmarksCount
isFollowingTag
}
}
"popularTags": [
{
"id": "81f2d610-1fa7-4397-86d2-9703b008d6a9",
"tag": "typescript",
"normalizedTag": "typescript",
"imageUrl": "https://readable-2021-dev.s3.ap-northeast-2.amazonaws.com/tags/typescript.jpg",
"followersCount": 1,
"userBookmarksCount": 4,
"isFollowingTag": true
},
```

✨ (server): Add popularTags query

---

apps/server/src/graphql-types.gql
apps/server/src/tags/applications/usercases/find-popular-tags-with-auth/find-popular-tags-with-auth.input.ts
apps/server/src/tags/applications/usercases/find-popular-tags-with-auth/find-popular-tags-with-auth.usecase.ts
apps/server/src/tags/tags.module.ts
apps/server/src/tags/tags.resolver.ts

♻️ (server): Change FindPopularTags from get to find

---

apps/server/src/graphql-types.gql
apps/server/src/tags/applications/usercases/find-popular-tags-with-auth/find-popular-tags-with-auth.usecase.ts
apps/server/src/tags/infrastructures/typeorm/repositories/tags.repository.ts
apps/server/src/users/applications/usecases/find-many-userBookmarks-having-users-with-auth/find-many-userBookmarks-having-users-with-auth.input.ts
apps/server/src/users/applications/usecases/find-many-userBookmarks-having-users-with-auth/find-many-userBookmarks-having-users-with-auth.usecase.ts
apps/server/src/users/infrastructures/typeorm/repositories/users.repository.ts
apps/server/src/users/users.module.ts
apps/server/src/users/users.resolver.ts

북마크 많은 유저 조회 Query
* No pagianation
* 몇 명 조회 `howMany` 입력

✨ (server): Add manyUserBookmarksHavingUsers query

---

apps/server/src/graphql-types.gql
apps/server/src/user-bookmark/applications/usecases/find-my-userBookmarks-grouped-by-interests/find-my-userBookmarks-grouped-by-interests.input.ts
apps/server/src/user-bookmark/applications/usecases/find-my-userBookmarks-grouped-by-interests/find-my-userBookmarks-grouped-by-interests.usecase.ts

```
{
"findMyUserBookmarksGroupedByInterestsInput": {
"limitOfInterests": 2,
"limitOfUserBookmarks": 2
}
}
```

♻️ (server): Change limits parameter of myUserBookmarksGroupedByInterests.

---

apps/server/src/graphql-types.gql
apps/server/src/users/applications/usecases/set-nickName/set-nickName.input.ts
apps/server/src/users/applications/usecases/set-nickName/set-nickName.usecase.ts
apps/server/src/users/domain/models/user.model.ts
apps/server/src/users/infrastructures/typeorm/entities/user.entity.ts
apps/server/src/users/users.module.ts
apps/server/src/users/users.resolver.ts

* Add `setNickname()` mutation.
```
{
"setNickNameInput" : {
"nickName": "teddy"
}
}
mutation SetNickname($setNickNameInput: SetNickNameInput!) {
setNickname(setNickNameInput: $setNickNameInput) {
id
name
nickName
provider
providerId
avatarUrl
followersCount
followingsCount
tags {
id
tag
}        
}
}
```

✨ (server): Add setNickname mutation

---

apps/server/src/graphql-types.gql
apps/server/src/pagination/pagination.module.ts
apps/server/src/pagination/pagination.service.ts
apps/server/src/pagination/tags/applications/usecases/get-pagination-tags/get-pagination-tags.usecase.ts
apps/server/src/pagination/userBookmarks/applications/usecases/get-pagination-recommended-user-bookmarks-by-tags/get-pagination-recommended-user-bookmarks-by-tags.input.ts
apps/server/src/pagination/userBookmarks/applications/usecases/get-pagination-recommended-user-bookmarks-by-tags/get-pagination-recommended-user-bookmarks-by-tags.usecase.ts
apps/server/src/pagination/userBookmarks/paginationUserBookmarks.resolver.ts
apps/server/src/tags/infrastructures/typeorm/repositories/tags.repository.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts

* Add `paginationRecommendedUserBookmarksByTags()` usecase

✨  (server): Add paginationRecommendedUserBookmarksByTags() usecase

---

apps/server/src/common/infrastructures/typeorm/entities/index.ts
apps/server/src/user-bookmark/infrastructures/typeorm/entities/user-bookmark.entity.ts

* Add index in `userBookmark`.
* Actually I need uuid in sequerce like mongo `ObjectId`.

♻️ (server): Add index in userBookmark

---

apps/server/src/user-bookmark/user-bookmark.resolver.ts

* Temp block `userBookmark` field resolver for preventing 1+N problem

🚧 (server): Block field resolve for preventing 1+N problem

---

apps/client/pages/[userId]/index.tsx
apps/client/pages/index.tsx
libs/collection/feature-collection/src/lib/feature-collection.tsx
libs/ui/src/lib/avatar/avatar.tsx
libs/ui/src/lib/card/shadow-card/shadow-card-summary.tsx
libs/ui/src/lib/profile/profile-card.tsx
libs/ui/src/lib/profile/profile-dashboard.tsx

- 마이 페이지 프로필 부분 반응형 UI 적용
- 홈 페이지에 깨진 프로필, 피드 카드 수정
(아이디 작업 전 묵은 브랜치 마스터 머지 작업...!)

💄 (client): Apply responsive UI to my page

---

libs/login/feature-login/src/lib/login-page.tsx

💄 (libs): Use only Google login

---

apps/server/src/graphql-types.gql
apps/server/src/user-bookmark/domain/model/user-bookmark.model.ts
apps/server/src/user-bookmark/infrastructures/typeorm/repositories/user-bookmark.repository.ts
apps/server/src/user-bookmark/user-bookmark.resolver.ts
apps/server/src/users/applications/usecases/create-test-users/create-test-users.usecase.ts

* Add userBookmark.user field resolver who bookmarked
* Set `nickName` when initial generating user information.

✨ (server): Add userBookmark.user field resolver who bookmarked

---

libs/home/data-access-home/src/lib/data-access-feed.query.generated.tsx
libs/home/data-access-home/src/lib/data-access-feed.query.tsx
libs/shared/types/src/lib/graphql-types.ts

* Update user information in `userBookmark` card using new field resolver

♻️ (libs): Update bookmark.user using field resolver

---

libs/home/data-access-home/src/lib/data-access-feed.query.generated.tsx
libs/home/data-access-home/src/lib/data-access-feed.query.tsx
libs/shared/types/src/lib/graphql-types.ts

Revert "♻️ (libs): Update bookmark.user using field resolver"

---

apps/server/src/users/infrastructures/typeorm/repositories/users.repository.ts

* Use `user.nickName` in popular Collector query

♻️ (server): Use nickName in popular collector query

---

.eslintrc.json
package.json
yarn.lock

* Enable unused-import-remove eslint rule

🚨 (common): Enable unused-import-remove eslint rule
